[package]
name = "firestore-query"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.10.0"
prost-types = "0.10.0"
serde_json = "1.0.96"
serde = { version = "1.0.136", features = [ "derive" ] }
tokio = { version = "1.18.5", features = [ "full" ] }
tonic = { version = "0.7.1", features = [ "tls", "tls-roots" ] }

[build-dependencies]
tonic-build = "0.7.0"
